# app.yaml

runtime: python312

entrypoint: gunicorn -b :$PORT __init__:app  # Correct the entry point to match your main app file

env_variables:


handlers:
  - url: /static
    static_dir: static  # Serves static files like CSS, JS, and images

  - url: /.*
    script: auto  # Automatically handles routing based on the Flask app

